apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xafrun

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/name: xafrun
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/omilun/xafrun-backend
    newTag: "0.2.1"
  - name: ghcr.io/omilun/xafrun-frontend
    newTag: "0.2.1"
