apiVersion: v1
kind: ServiceAccount
metadata:
  name: xafrun-backend
  namespace: xafrun
  labels:
    app.kubernetes.io/name: xafrun
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kustomize
