apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluxbaan-backend
  namespace: fluxbaan
  labels:
    app.kubernetes.io/name: fluxbaan
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kustomize
