apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxbaan.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluxbaan.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "fluxbaan.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
