apiVersion: v1
kind: Service
metadata:
  name: {{ include "xafrun.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xafrun.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "xafrun.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
