{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xafrun.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xafrun.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "xafrun.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 3000
{{- end }}
